version: "3.2"

networks: data-service-network

services:
  data-provider:
    image: data-provider
    container_name: "data-provider"
    ports:
      - 9999:8081
    networks: data-service-network

  data-consumer:
    image: ./dockerfile
    container_name: "data-consumer"
    ports:
      - 8080:80
    networks:
      data-service-network

      #https://saggu.medium.com/how-to-connect-nultiple-docker-conatiners-17f7ca72e67f
